name: Desplegar Multi-PWA Monorepo a GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

# Variables de entorno del servidor
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
  NODE_OPTIONS: '--no-deprecation' # <--- ESTO OCULTA LA ADVERTENCIA DE PUNYCODE

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm' # Reactivado con seguridad gracias al lockfile sano de la raíz
          
      - name: Instalar Dependencias
        run: npm install
        
      - name: Ejecutar Compilación Unificada
        run: npm run build:all
           
      - name: Inyectar Enrutamientos Fallback 404
        run: |
          cp dist/pwa-app1/index.html dist/pwa-app1/404.html
          cp dist/pwa-app2/index.html dist/pwa-app2/404.html
          cp dist/index.html dist/404.html
             
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
      - uses: actions/deploy-pages@v4
